name: Closing capture

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Capture closing odds around KO
        run: |
          set -euo pipefail
          curl -fsS "https://predictscores.vercel.app/api/cron/closing-capture"
