name: Closing capture

on:
  schedule:
    - cron: "*/10 8-23 * * *"
  workflow_dispatch: {}

concurrency:
  group: closing-capture
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 4
    steps:
      - name: Capture closings (cheap & robust)
        run: |
          set -euo pipefail
          curl -fsS \
            --connect-timeout 10 \
            --max-time 180 \
            --retry 3 \
            --retry-all-errors \
            --retry-delay 8 \
            --retry-max-time 240 \
            "https://predictscores.vercel.app/api/cron/closing-capture?days=1"

          echo "✅ closing-capture done" >> $GITHUB_STEP_SUMMARY
