name: Closing capture

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

env:
  BASE: ${{ secrets.BASE_URL }}
  FALLBACK_BASE: https://predictscores.vercel.app

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Capture closing odds around KO
        run: |
          set -euo pipefail
          B="${BASE:-$FALLBACK_BASE}"
          curl -fsS "$B/api/cron/closing-capture"
