name: Crypto Watchdog

on:
  schedule:
    - cron: "0 * * * *"    # svaka puna ura (minute 00)
    - cron: "30 * * * *"   # minute 30 svake ure
  workflow_dispatch: {}     # ručni trigger iz Actions taba

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Validate secrets
        env:
          BASE_URL: ${{ secrets.BASE_URL }}
          CRON_KEY: ${{ secrets.CRON_KEY }}
        run: |
          set -e
          if [ -z "$BASE_URL" ]; then
            echo "ERROR: BASE_URL secret is missing."; exit 1; fi
          if [ -z "$CRON_KEY" ]; then
            echo "ERROR: CRON_KEY secret is missing."; exit 1; fi
          if ! echo "$BASE_URL" | grep -Eq '^https?://'; then
            echo "ERROR: BASE_URL must include scheme (https://). Current: '$BASE_URL'"; exit 1; fi

      - name: Call crypto-watchdog
        env:
          BASE_URL: ${{ secrets.BASE_URL }}
          CRON_KEY: ${{ secrets.CRON_KEY }}
        run: |
          set -euo pipefail
          curl --fail --show-error --silent \
            "$BASE_URL/api/cron/crypto-watchdog?key=$CRON_KEY" \
            | tee /dev/stderr
