name: History settle (scores)

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

env:
  BASE: ${{ secrets.BASE_URL }}
  FALLBACK_BASE: https://predictscores.vercel.app

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Settle last 2 days
        run: |
          set -euo pipefail
          B="${BASE:-$FALLBACK_BASE}"
          curl -fsS "$B/api/history-check?days=2"
