name: History settle (scores)

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Settle last 2 days
        run: |
          set -euo pipefail
          curl -fsS "https://predictscores.vercel.app/api/history-check?days=2"
