name: snapshots

on:
  workflow_dispatch: {}
  push:
    branches:
      - main
  schedule:
    # 00:00 Europe/Belgrade  ≈ 22:00 UTC (tokom CEST)
    - cron: '0 22 * * *'
    # 10:00 Europe/Belgrade ≈ 08:00 UTC
    - cron: '0 8 * * *'
    # 15:00 Europe/Belgrade ≈ 13:00 UTC
    - cron: '0 13 * * *'

concurrency:
  group: snapshots-${{ github.ref }}
  cancel-in-progress: false

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      BASE_URL: https://predictscores.vercel.app
    steps:
      - name: Compute slot (Europe/Belgrade)
        id: slot
        run: |
          H=$(TZ='Europe/Belgrade' date +%H)
          if [ "$H" -lt 10 ]; then SLOT=late;
          elif [ "$H" -lt 15 ]; then SLOT=am;
          else SLOT=pm; fi
          echo "slot=$SLOT" >> $GITHUB_OUTPUT
          echo "Belgrade hour: $H, slot: $SLOT"

      - name: Rebuild snapshot
        run: curl -fsSL "$BASE_URL/api/cron/rebuild?slot=${{ steps.slot.outputs.slot }}&debug=1"

      - name: Refresh odds (OA→AF, median & consensus)
        run: curl -fsSL "$BASE_URL/api/cron/refresh-odds?slot=${{ steps.slot.outputs.slot }}"

      - name: Apply learning (history settle/calibration hook)
        run: curl -fsSL "$BASE_URL/api/cron/apply-learning?debug=1"

      - name: Build insights / freeze tickets
        run: curl -fsSL "$BASE_URL/api/insights-build?slot=${{ steps.slot.outputs.slot }}&debug=1"
