name: snapshots

on:
  # Keep manual runs
  workflow_dispatch: {}
  # Run ONLY on schedule (Belgrade time windows)
  schedule:
    # 00:00 Europe/Belgrade
    - cron: '0 22 * * *'   # UTC==22 → 00:00 CET/CEST
    # 10:00 Europe/Belgrade
    - cron: '0 8 * * *'    # UTC==08 → 10:00 CET/CEST
    # 15:00 Europe/Belgrade
    - cron: '0 13 * * *'   # UTC==13 → 15:00 CET/CEST

# No push/PR triggers → no accidental API calls on merges

concurrency:
  group: learning
  cancel-in-progress: true

jobs:
  learning:
    runs-on: ubuntu-latest
    timeout-minutes: 8
    env:
      BASE_URL: ${{ vars.BASE_URL || secrets.BASE_URL || 'https://predictscores.vercel.app' }}
    permissions:
      contents: read
    steps:
      - name: Compute Belgrade slot
        id: slot
        run: |
          set -euo pipefail
          TZZ="Europe/Belgrade"
          H=$(TZ=$TZZ date +%H)
          if [ "$H" -lt 10 ]; then SLOT=late;
          elif [ "$H" -lt 15 ]; then SLOT=am;
          else SLOT=pm; fi
          echo "slot=$SLOT" >> $GITHUB_OUTPUT
          echo "Belgrade hour: $H, slot: $SLOT"

      - name: Rebuild candidate snapshot
        run: curl -fsSL "$BASE_URL/api/cron/rebuild?slot=${{ steps.slot.outputs.slot }}&debug=1"

      - name: Refresh odds (AF consensus/median)
        run: curl -fsSL "$BASE_URL/api/cron/refresh-odds?slot=${{ steps.slot.outputs.slot }}"

      - name: Apply learning (writes vb:day:<ymd>:last)
        run: curl -fsSL "$BASE_URL/api/cron/apply-learning?debug=1"

      - name: Build insights / freeze tickets
        run: curl -fsSL "$BASE_URL/api/insights-build?slot=${{ steps.slot.outputs.slot }}&debug=1"
