# FILE: .github/workflows/learning.yml
name: Nightly Learning (14d)

on:
  schedule:
    - cron: "15 22 * * *"   # 00:15 lokalno (Europe/Belgrade) = 22:15 UTC
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Aggregate & write overlay/evmin
        run: |
          curl -fsS "https://predictscores.vercel.app/api/cron/learn?days=14"
