name: Nightly Learning (14d)

on:
  schedule:
    - cron: "15 22 * * *"   # 00:15 Europe/Belgrade
  workflow_dispatch: {}

env:
  BASE: ${{ secrets.BASE_URL }}
  FALLBACK_BASE: https://predictscores.vercel.app

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Learn over last 14 days
        run: |
          set -euo pipefail
          B="${BASE:-$FALLBACK_BASE}"
          curl -fsS "$B/api/cron/learn?days=14"
