name: Learning (nightly)

on:
  schedule:
    - cron: '30 2 * * *'  # 02:30 UTC
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Call learn
        run: |
          set -e
          curl -fsS https://predictscores.vercel.app/api/cron/learn
