name: Odds watcher

on:
  schedule:
    # svakih 10 min, pomereno da se manje sudara sa ostalima
    - cron: '1-59/10 * * * *'
  workflow_dispatch:

env:
  BASE: ${{ secrets.BASE_URL }}
  FALLBACK_BASE: https://predictscores.vercel.app

concurrency:
  group: odds-watcher
  cancel-in-progress: false

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 4
    steps:
      - name: Warmup (quick ping)
        run: |
          set -euo pipefail
          B="${BASE:-$FALLBACK_BASE}"
          curl -fsS --connect-timeout 5 --max-time 10 "$B/api/ping" | cat || true

      - name: Refresh odds window (retry + backoff)
        run: |
          set -euo pipefail
          B="${BASE:-$FALLBACK_BASE}"
          tries=4
          delay=4
          for i in $(seq 1 $tries); do
            echo "Attempt $i/$tries..."
            if curl -fsS --ipv4 --connect-timeout 10 --max-time 60 "$B/api/cron/refresh-odds"; then
              echo "OK"; exit 0
            fi
            echo "Retrying in ${delay}s..."
            sleep $delay
            delay=$(( delay * 2 ))
          done
          echo "All attempts failed"; exit 1
