name: Odds watcher

on:
  schedule:
    - cron: "*/15 8-23 * * *"
  workflow_dispatch: {}

concurrency:
  group: odds-watcher
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      # koristi taj koji postoji: secret ili var (case-insensitive fallback)
      BASE_URL: ${{ secrets.BASE_URL || vars.BASE_URL || vars.base_url }}

    steps:
      - name: Validate BASE_URL
        run: |
          set -euo pipefail
          if [ -z "${BASE_URL:-}" ]; then
            echo "::error::BASE_URL is empty. Add it in GitHub → Settings → Secrets and variables → Actions."
            exit 1
          fi
          if ! echo "$BASE_URL" | grep -Eqi '^https?://'; then
            echo "::error::BASE_URL must start with http:// or https:// (got: $BASE_URL)"
            exit 1
          fi

      - name: Refresh odds window for current slot
        run: |
          set -euo pipefail

          TZZ="Europe/Belgrade"
          H=$(TZ=$TZZ date +%H)
          if   [ "$H" -lt 10 ]; then SLOT=late
          elif [ "$H" -lt 15 ]; then SLOT=am
          else SLOT=pm; fi
          echo "Slot: $SLOT"

          curl -fsS \
            --connect-timeout 10 \
            --max-time 240 \
            --retry 3 \
            --retry-all-errors \
            --retry-delay 8 \
            --retry-max-time 300 \
            "$BASE_URL/api/cron/refresh-odds?slot=$SLOT"

          echo "✅ refresh-odds done for slot=$SLOT" >> $GITHUB_STEP_SUMMARY
