name: Odds watcher

on:
  schedule:
    - cron: '1-59/10 * * * *'
  workflow_dispatch:

env:
  BASE: ${{ secrets.BASE_URL }}
  FALLBACK_BASE: https://predictscores.vercel.app

concurrency:
  group: odds-watcher
  cancel-in-progress: false

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 4
    steps:
      - name: Resolve BASE, SLOT and YMD
        id: ctx
        run: |
          set -euo pipefail
          BASE="${BASE:-}"
          if [ -z "$BASE" ]; then BASE="$FALLBACK_BASE"; fi
          echo "base=$BASE" >> $GITHUB_OUTPUT

          H=$(TZ=Europe/Belgrade date +%H)
          if   [ "$H" -lt 10 ]; then SLOT="late"
          elif [ "$H" -lt 15 ]; then SLOT="am"
          else                         SLOT="pm"
          fi
          echo "slot=$SLOT" >> $GITHUB_OUTPUT
          YMD=$(TZ=Europe/Belgrade date +%F)
          echo "ymd=$YMD" >> $GITHUB_OUTPUT

      - name: Warmup (quick ping)
        run: |
          set -euo pipefail
          curl -fsS --connect-timeout 5 --max-time 10 "${{ steps.ctx.outputs.base }}/api/ping" | cat || true

      - name: Refresh odds window for current slot
        run: |
          set -euo pipefail
          curl -fsS --ipv4 --connect-timeout 10 --max-time 60 "${{ steps.ctx.outputs.base }}/api/cron/refresh-odds?slot=${{ steps.ctx.outputs.slot }}&ymd=${{ steps.ctx.outputs.ymd }}"
