name: Odds watcher

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Refresh odds
        run: |
          set -euo pipefail
          curl -fsS "https://predictscores.vercel.app/api/cron/refresh-odds"
