# FILE: .github/workflows/odds-watcher.yml
name: Odds watcher (refresh prices)

on:
  schedule:
    - cron: "*/10 * * * *"   # svakih 10 min (UTC) tokom dana
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Refresh odds once
        run: |
          curl -fsS "https://predictscores.vercel.app/api/cron/refresh-odds" || true
