name: Odds watcher

on:
  schedule:
    - cron: "*/15 8-23 * * *"   # svakih 15min, 08–23h
  workflow_dispatch: {}

concurrency:
  group: odds-watcher
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Refresh odds window for current slot
        env:
          BASE_URL: ${{ secrets.BASE_URL }}   # npr. https://predictscores.vercel.app
        run: |
          set -euo pipefail

          TZZ="Europe/Belgrade"
          H=$(TZ=$TZZ date +%H)
          if   [ "$H" -lt 10 ]; then SLOT=late
          elif [ "$H" -lt 15 ]; then SLOT=am
          else SLOT=pm; fi

          echo "Slot: $SLOT"

          curl -fsS \
            --connect-timeout 10 \
            --max-time 240 \
            --retry 3 \
            --retry-all-errors \
            --retry-delay 8 \
            --retry-max-time 300 \
            "$BASE_URL/api/cron/refresh-odds?slot=$SLOT"

          echo "✅ refresh-odds done for slot=$SLOT" >> $GITHUB_STEP_SUMMARY
