name: Refresh odds smoke

on:
  push:
  pull_request:

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Check for conflict markers
        run: |
          if git grep -n '<<<<<<<\\|=======\\|>>>>>>>' --; then
            echo "Conflict markers detected"
            exit 1
          fi

      - name: Refresh odds smoke test
        run: npm run smoke:refresh-odds
