name: Smoke

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 18.17
        uses: actions/setup-node@v4
        with:
          node-version: 18.17.0
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Smoke history endpoint
        env:
          BASE: https://predictscores-mock.vercel.app
        run: node scripts/smoke-history.mjs
