name: Vercel Deploy Hook

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  trigger-vercel:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Vercel Deploy (force)
        env:
          HOOK: "https://api.vercel.com/v1/integrations/deploy/prj_zs9kf5e2NRdyDvFwI1LVhkRg0oBr/gWKzM5JmJY"
        run: |
          set -euxo pipefail
          curl -fsS -X POST "$HOOK?force=1"
