name: Vercel Deploy Hook
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  trigger-vercel:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Vercel Production Deploy
        run: |
          curl -fsSL -X POST "https://api.vercel.com/v1/integrations/deploy/prj_zs9kf5e2NRdyDvFwI1LVhkRg0oBr/gWKzM5JmJY"
